version: "3.8"

services:
  postgresql:
    image: postgres:14-alpine
    container_name: billy-pay-postgres-db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./init-postgres-dbs.sql:/docker-entrypoint-initdb.d/init-postgres-dbs.sql
  #    healthcheck:
  #      test: [ "CMD", "pg_isready", "-U", "postgres" ]
  #      interval: 10s
  #      timeout: 5s
  #      retries: 3

  pgadmin:
    image: dpage/pgadmin4:6.13
    container_name: billy-pay-pgadmin
    ports:
      - "5050:80"
    depends_on:
      - postgresql
#        condition: service_healthy
    environment:
      PGADMIN_DEFAULT_EMAIL: postgres@mail.com
      PGADMIN_DEFAULT_PASSWORD: postgres
    volumes:
      - pgadmin:/var/lib/pgadmin4/storage

  config-server:
    image: farrukhkh/billy-pay-config-server:1.0-SNAPSHOT
    container_name: billy-pay-config-server
    build:
      context: ./config-server
      dockerfile: Dockerfile
    ports:
      - "8090:8090"
  #    healthcheck:
  #      test: [ "CMD" ]
  #      interval: 10s
  #      timeout: 5s
  #      retries: 30

  eureka-server:
    image: farrukhkh/billy-pay-eureka-server:1.0-SNAPSHOT
    container_name: billy-pay-eureka-server
    build:
      context: ./eureka-server
      dockerfile: Dockerfile
    ports:
      - "8761:8761"
    #    healthcheck:
    #      test: [ "CMD" ]
    #      interval: 10s
    #      timeout: 5s
    #      retries: 30
    environment:
      CONFIG_SERVER_URL: http://config-server:8090

  bill:
    image: farrukhkh/billy-pay-bill:1.0-SNAPSHOT
    container_name: billy-pay-bill
    build:
      context: ./bill
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - config-server
      #        condition: service_healthy
      - eureka-server
      #        condition: service_healthy
      - postgresql
    #        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgresql:5432/bill
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: postgres
      CONFIG_SERVER_URL: http://config-server:8090
      EUREKA_SERVER_URL: http://eureka-server:8761


volumes:
  pgadmin:


networks:
    default:
      driver: bridge